volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
  redis-cluster_data-6:
    driver: local
  redis-cluster_data-7:
    driver: local
  redis-cluster_data-8:
    driver: local
  redis-cluster_data-9:
    driver: local
  redis-cluster_data-10:
    driver: local
  redis-cluster_data-11:
    driver: local
  redisinsight-data:
    driver: local


services:
  redis-node-0:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-1:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'
  
  redis-node-2:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-3:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-4:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-5:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-6:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-6:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-7:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-7:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-8:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-8:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-9:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-9:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-10:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-10:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'

  redis-node-11:
    image: bitnamilegacy/redis-cluster:8.2.1
    volumes:
      - redis-cluster_data-11:/bitnami/redis/data
    ports:
      - "6379:6379"
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-node-7
      - redis-node-8
      - redis-node-9
      - redis-node-10
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=3'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7 redis-node-8 redis-node-9 redis-node-10 redis-node-11'
      - 'REDIS_CLUSTER_CREATOR=yes'


  redis-insight:
    image: redis/redisinsight:3.0.1
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    environment:
      - REDISINSIGHT_ACCEPT_LICENSE=true
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-node-7
      - redis-node-8
      - redis-node-9
      - redis-node-10
      - redis-node-11

