global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "security"
    static_configs:
      - targets: ["security:3000"]  

  - job_name: "uploader"
    static_configs:
      - targets: ["uploader:3000"]

  - job_name: "storage"
    static_configs:
      - targets: ["storage:9000"]
    metrics_path: "/minio/v2/metrics/cluster"
